// SPDX-License-Identifier: GPL-2.0-only
//! Systemd actuator implementation.

use crate::platform::{Actuator, DropinFormat};
use crate::platform::init::{is_root, root_cmd, sudo, sudo_tee_secret};
use anyhow::Result;
use std::path::{Path, PathBuf};
use std::process::Command;

pub const ETC_UNIT_DIR: &str = "/etc/systemd/system";
pub const RUN_UNIT_DIR: &str = "/run/systemd/system";
const VENDOR_UNIT_DIRS: &[&str] = &["/usr/lib/systemd/system", "/lib/systemd/system"];

fn etc_units_writable() -> bool {
    let nixos = Path::new("/etc/NIXOS").exists();
    let canon = std::fs::canonicalize(ETC_UNIT_DIR).ok();
    let mounts = std::fs::read_to_string("/proc/self/mounts").unwrap_or_default();
    etc_units_writable_from(nixos, canon.as_deref(), &mounts)
}

fn etc_units_writable_from(nixos_marker: bool, canon: Option<&Path>, mounts: &str) -> bool {
    if nixos_marker {
        return false;
    }
    if canon.is_some_and(|c| c.starts_with("/nix/store")) {
        return false;
    }
    !mounted_ro(mounts, Path::new(ETC_UNIT_DIR))
}

fn mounted_ro(mounts: &str, path: &Path) -> bool {
    let mut best: Option<(usize, bool)> = None;
    for line in mounts.lines() {
        let mut f = line.split_whitespace();
        let (Some(_dev), Some(mp), Some(_fs), Some(opts)) =
            (f.next(), f.next(), f.next(), f.next())
        else {
            continue;
        };
        let mp = mp.replace("\\040", " ").replace("\\011", "\t");
        if path.starts_with(Path::new(&mp)) {
            let ro = opts.split(',').any(|o| o == "ro");
            if best.is_none_or(|(len, _)| mp.len() >= len) {
                best = Some((mp.len(), ro));
            }
        }
    }
    best.is_some_and(|(_, ro)| ro)
}

pub fn unit_install_dir() -> &'static str {
    if etc_units_writable() {
        ETC_UNIT_DIR
    } else {
        RUN_UNIT_DIR
    }
}

pub fn dropin_dir(unit: &str) -> PathBuf {
    PathBuf::from(format!("{}/{unit}.d", unit_install_dir()))
}

fn dropin_scan_dirs(unit: &str) -> Vec<PathBuf> {
    let mut roots = vec![ETC_UNIT_DIR, RUN_UNIT_DIR];
    roots.extend(VENDOR_UNIT_DIRS);
    roots
        .into_iter()
        .map(|r| PathBuf::from(format!("{r}/{unit}.d")))
        .collect()
}

const MARKER: &str = "AUTO-GENERATED by llmtune [model-select]";
const LLMTUNE_PREFIX: &str = "AUTO-GENERATED by llmtune";

fn collect_dropins(unit: &str) -> (Vec<PathBuf>, Vec<String>) {
    let install = unit_install_dir();
    let dirs: Vec<(PathBuf, bool)> = dropin_scan_dirs(unit)
        .into_iter()
        .map(|d| {
            let writable = d.starts_with(install) || d.starts_with(RUN_UNIT_DIR);
            (d, writable)
        })
        .collect();
    collect_dropins_in(&dirs, |t| t.contains(MARKER))
}

fn collect_dropins_in(
    dirs: &[(PathBuf, bool)],
    is_ours: impl Fn(&str) -> bool,
) -> (Vec<PathBuf>, Vec<String>) {
    let mut ours = Vec::new();
    let mut foreign = Vec::new();
    for (d, writable) in dirs {
        let (o, mut f) = scan_dropins(d, &is_ours);
        if *writable {
            ours.extend(o);
        } else {
            foreign.extend(
                o.iter()
                    .filter_map(|p| p.file_name().map(|n| n.to_string_lossy().into_owned())),
            );
        }
        foreign.append(&mut f);
    }
    (ours, foreign)
}

fn scan_dropins(dir: &Path, is_ours: &dyn Fn(&str) -> bool) -> (Vec<PathBuf>, Vec<String>) {
    let mut ours = Vec::new();
    let mut foreign = Vec::new();
    if let Ok(rd) = std::fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().and_then(|x| x.to_str()) != Some("conf") {
                continue;
            }
            if is_ours(&read_dropin(&p)) {
                ours.push(p);
            } else {
                foreign.push(e.file_name().to_string_lossy().into_owned());
            }
        }
    }
    (ours, foreign)
}

fn read_dropin(path: &Path) -> String {
    if let Ok(s) = std::fs::read_to_string(path) {
        if !s.is_empty() || is_root() {
            return s;
        }
    }
    if is_root() {
        return "".to_string();
    }
    Command::new(root_cmd())
        .args(["cat", &path.to_string_lossy()])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .unwrap_or_default()
}

fn winning_name(foreign: &[String]) -> String {
    let base = "zzzzzz-llmtune.conf".to_string();
    match foreign.iter().max() {
        Some(m) if m.as_str() >= base.as_str() => {
            let stem = m.strip_suffix(".conf").unwrap_or(m);
            format!("{stem}z-llmtune.conf")
        }
        _ => base,
    }
}

pub struct SystemdActuator {
    wrote: Option<PathBuf>,
    removed_self: Option<(PathBuf, String)>,
    backup_dir: PathBuf,
}

impl SystemdActuator {
    pub fn new() -> Self {
        SystemdActuator {
            wrote: None,
            removed_self: None,
            backup_dir: PathBuf::from("/var/lib/llmtune/backups"),
        }
    }
}

impl Default for SystemdActuator {
    fn default() -> Self {
        Self::new()
    }
}

impl Actuator for SystemdActuator {
    fn stage(&mut self, unit: &str, dropin_content: &str, _fmt: DropinFormat) -> Result<()> {
        let dir = dropin_dir(unit);
        let (ours, foreign) = collect_dropins(unit);
        for (i, p) in ours.iter().enumerate() {
            if i == 0 {
                let content = read_dropin(p);
                let _ = sudo(&["mkdir", "-p", &self.backup_dir.to_string_lossy()]);
                let _ = sudo_tee_secret(
                    &self.backup_dir.join(format!("{unit}.dropin.prev")),
                    &content,
                );
                self.removed_self = Some((p.clone(), content));
            }
            let _ = sudo(&["rm", "-f", &p.to_string_lossy()]);
        }
        let path = dir.join(winning_name(&foreign));
        sudo(&["mkdir", "-p", &dir.to_string_lossy()])?;
        sudo_tee_secret(&path, dropin_content)?;
        self.wrote = Some(path);
        Ok(())
    }

    fn rollback(&mut self, _unit: &str) -> Result<()> {
        if let Some(p) = self.wrote.take() {
            sudo(&["rm", "-f", &p.to_string_lossy()])?;
        }
        if let Some((p, c)) = self.removed_self.take() {
            sudo_tee_secret(&p, &c)?;
        }
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        self.removed_self = None;
        Ok(())
    }

    fn restart(&mut self, unit: &str) -> Result<()> {
        sudo(&["systemctl", "daemon-reload"])?;
        let _ = sudo(&["systemctl", "reset-failed", unit]);
        sudo(&["systemctl", "restart", unit])?;
        Ok(())
    }
}
