// SPDX-License-Identifier: GPL-2.0-only
//! The netboot (PXE) control plane.
//!
//! llmtune turns a spare host into a BC-250 boot server WITHOUT reinventing the
//! network stack: it orchestrates a proxyDHCP `dnsmasq` (answers only PXE, leaves
//! IP assignment to the LAN router) plus an NFS root, and EMBEDS the artifact +
//! iPXE server (`tiny_http`, already a dep) so it controls exactly what each
//! board boots. A booted board is discovered from the dnsmasq lease file and
//! auto-registered into `fleet.toml` as an `ssh` node, so it flows straight into
//! the fleet cockpit and the `node`/`fleet`/`cluster` commands.
//!
//! Boot chain: firmware PXE -> dnsmasq hands `ipxe.efi` over its built-in TFTP ->
//! iPXE re-requests -> dnsmasq points it at `http://<server>:<port>/boot.ipxe` ->
//! llmtune serves a kernel + NFS-root cmdline -> diskless CachyOS.
//!
//! The config GENERATORS are pure functions (unit-tested); the orchestrator does
//! the privileged IO and previews by default (`--apply` to write), mirroring the
//! rest of llmtune's write commands.

use anyhow::{bail, Context, Result};
use std::path::Path;

use crate::config::Netboot;

/// A resolved netboot config or a clear error explaining it is unconfigured.
pub fn require(cfg: &crate::config::Config) -> Result<&Netboot> {
	cfg.netboot.as_ref().ok_or_else(|| {
		anyhow::anyhow!(
			"netboot is not configured - add a [netboot] section to fleet.toml \
			 (interface, server_ip, subnet). See `llmtune netboot init --help`."
		)
	})
}

// ---------------------------------------------------------------------------
// Pure config generators (unit-tested).
// ---------------------------------------------------------------------------

/// The proxyDHCP dnsmasq config. proxyDHCP answers ONLY the PXE boot options and
/// leaves address assignment to the LAN's existing DHCP server, so it is safe to
/// run on a shared network (it will not fight the router). Stage 1 hands EFI
/// clients the iPXE NBP over dnsmasq's built-in TFTP; stage 2 (iPXE now running,
/// tagged by its user-class) points at llmtune's HTTP boot script.
pub fn dnsmasq_conf(nb: &Netboot) -> String {
	format!(
		"# AUTO-GENERATED by llmtune (`llmtune netboot init`). Edit fleet.toml,\n\
		 # not this file - re-running init overwrites it.\n\
		 # proxyDHCP: PXE-only, the LAN router still assigns IPs.\n\
		 port=0\n\
		 log-dhcp\n\
		 dhcp-no-override\n\
		 \n\
		 # Only serve PXE on the boot NIC; never assign addresses.\n\
		 interface={iface}\n\
		 bind-interfaces\n\
		 dhcp-range={subnet},proxy\n\
		 \n\
		 # Client-arch + iPXE detection.\n\
		 dhcp-match=set:efi64,option:client-arch,7\n\
		 dhcp-match=set:efi64,option:client-arch,9\n\
		 dhcp-userclass=set:ipxe,iPXE\n\
		 \n\
		 # Stage 1: firmware -> iPXE NBP over TFTP. Stage 2: iPXE -> HTTP script.\n\
		 dhcp-boot=tag:efi64,tag:!ipxe,ipxe.efi,,{ip}\n\
		 dhcp-boot=tag:ipxe,{base}/boot.ipxe\n\
		 \n\
		 # dnsmasq's built-in TFTP serves only ipxe.efi (no tftp-hpa needed).\n\
		 enable-tftp\n\
		 tftp-root={tftp}\n",
		iface = nb.interface,
		subnet = nb.subnet,
		ip = nb.server_ip,
		base = nb.http_base(),
		tftp = nb.tftp_root,
	)
}

/// The `/etc/exports` line for the read-only diskless root.
///
/// Deliberate posture, documented in the README's security notes:
/// `ro` (nodes never write the shared root) + `no_root_squash` (the diskless
/// nodes' root must read root-owned files in the image). The export CIDR IS
/// the security boundary - every host inside it can read the full root image,
/// so `lan_cidr` must be the narrow fleet subnet, never a wide range.
pub fn nfs_exports(nb: &Netboot) -> String {
	format!(
		"# AUTO-GENERATED by llmtune (`llmtune netboot init`).\n\
		 {root} {cidr}(ro,sync,no_subtree_check,no_root_squash)\n",
		root = nb.rootfs,
		cidr = nb.export_cidr(),
	)
}

/// The dynamic iPXE boot script llmtune serves at `/boot.ipxe`. `mac` (when the
/// board passes `${net0/mac}`) lets a future per-node override vary the profile;
/// for now every board gets the same NFS-root boot with the configured OC
/// profile baked into the kernel cmdline for the image's tuner to read.
pub fn boot_ipxe(nb: &Netboot, _mac: Option<&str>) -> String {
	format!(
		"#!ipxe\n\
		 kernel {base}/vmlinuz root=nfs:{ip}:{root} ip=dhcp rw rd.neednet=1 \
		 amd_pstate=passive idle=amd_hwp llmtune.oc={oc}\n\
		 initrd {base}/initramfs-nfs.img\n\
		 boot\n",
		base = nb.http_base(),
		ip = nb.server_ip,
		root = nb.rootfs,
		oc = nb.oc_profile,
	)
}

/// The systemd unit that runs llmtune's artifact/iPXE server. `exe` is llmtune's
/// own path so the unit survives a binary move only if reinstalled in place (the
/// same contract as `setup`'s generated unit).
pub fn http_unit(exe: &str, user: &str, port: u16, config: Option<&str>) -> String {
	let cfg_arg = config.map(|c| format!(" --config {c}")).unwrap_or_default();
	format!(
		"# AUTO-GENERATED by llmtune (`llmtune netboot init`).\n\
		 [Unit]\n\
		 Description=llmtune netboot artifact + iPXE server\n\
		 After=network-online.target\n\
		 Wants=network-online.target\n\
		 \n\
		 [Service]\n\
		 ExecStart={exe} netboot serve --port {port}{cfg_arg}\n\
		 Restart=on-failure\n\
		 RestartSec=2\n\
		 User={user}\n\
		 \n\
		 [Install]\n\
		 WantedBy=multi-user.target\n",
	)
}

/// The unit name llmtune manages for the netboot HTTP server.
pub const HTTP_UNIT: &str = "llmtune-netboot.service";
/// The dnsmasq config path llmtune writes.
pub const DNSMASQ_CONF: &str = "/etc/dnsmasq.d/llmtune-netboot.conf";
/// The NFS exports drop-in llmtune writes.
pub const EXPORTS_CONF: &str = "/etc/exports.d/llmtune-netboot.exports";

// ---------------------------------------------------------------------------
// Discovery: which BC-250s have netbooted (dnsmasq lease file).
// ---------------------------------------------------------------------------

/// A single DHCP lease as reported by the boot server.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lease {
	pub mac: String,
	pub ip: String,
	pub hostname: String,
	pub expiry: u64,
}

/// Parse a dnsmasq lease file. Each line is `<expiry> <mac> <ip> <hostname>
/// <clientid>`; a `*` hostname means unknown. Malformed lines are skipped.
pub fn parse_leases(text: &str) -> Vec<Lease> {
	text.lines()
		.filter_map(|l| {
			let mut f = l.split_whitespace();
			let expiry = f.next()?.parse::<u64>().ok()?;
			let mac = f.next()?.to_lowercase();
			// The lease file is attacker-influenced (any DHCP client names
			// itself), and the IP becomes an ssh target - require a literal
			// IPv4 address so a crafted lease can't smuggle anything else
			// into the argv (defense in depth on top of the `--` ssh guard).
			let ip = f.next()?.parse::<std::net::Ipv4Addr>().ok()?.to_string();
			let hostname = f.next().unwrap_or("*").to_string();
			if mac.split(':').count() != 6 {
				return None;
			}
			Some(Lease {
				mac,
				ip,
				hostname,
				expiry,
			})
		})
		.collect()
}

/// Parse `ip -4 neigh show` output into (ip, mac) pairs. Lines look like
/// `198.51.100.223 dev enp2s0f0np0 lladdr 00:00:5e:00:53:63 REACHABLE`; entries
/// without an lladdr (FAILED/INCOMPLETE) are skipped.
pub fn parse_neigh(text: &str) -> Vec<(String, String)> {
	text.lines()
		.filter_map(|l| {
			let f: Vec<&str> = l.split_whitespace().collect();
			let ip = (*f.first()?).to_string();
			let mac = f
				.iter()
				.position(|&w| w == "lladdr")
				.and_then(|i| f.get(i + 1))?
				.to_lowercase();
			if mac.split(':').count() != 6 || ip.parse::<std::net::Ipv4Addr>().is_err() {
				return None;
			}
			Some((ip, mac))
		})
		.collect()
}

/// Turn neighbor-table entries into discovery leases. The neighbor table has
/// no hostname, so a board is only identifiable by MAC OUI - with no
/// `mac_ouis` configured this yields nothing (rather than claiming every LAN
/// device is a BC-250). Discovered boards get the `bc250-<mac6>` name via
/// [`node_name`]'s fallback.
pub fn discover_neigh(nb: &Netboot, pairs: &[(String, String)]) -> Vec<Lease> {
	if nb.mac_ouis.is_empty() {
		return Vec::new();
	}
	pairs
		.iter()
		.filter(|(_, mac)| nb.mac_ouis.iter().any(|o| mac.starts_with(o)))
		.map(|(ip, mac)| Lease {
			mac: mac.clone(),
			ip: ip.clone(),
			hostname: "*".into(),
			expiry: 0,
		})
		.collect()
}

/// Merge two discovery sources, deduplicating by MAC. Earlier sources win, so
/// pass the richer one (leases carry a hostname; the neighbor table does not)
/// first.
pub fn merge_discovered(primary: Vec<Lease>, secondary: Vec<Lease>) -> Vec<Lease> {
	let mut out = primary;
	for l in secondary {
		if !out.iter().any(|e| e.mac == l.mac) {
			out.push(l);
		}
	}
	out
}

/// Filter leases down to the BC-250s: by MAC OUI prefix if configured, else by
/// the hostname prefix. A lease matches an OUI if its MAC starts with it.
pub fn discover(nb: &Netboot, leases: &[Lease]) -> Vec<Lease> {
	leases
		.iter()
		.filter(|l| {
			if !nb.mac_ouis.is_empty() {
				nb.mac_ouis.iter().any(|o| l.mac.starts_with(o))
			} else {
				l.hostname.to_lowercase().starts_with(&nb.hostname_prefix)
			}
		})
		.cloned()
		.collect()
}

/// A short, stable, fleet-safe node name for a discovered board: the hostname if
/// it is usable, else `bc250-<last-3-mac-octets>`.
pub fn node_name(nb: &Netboot, l: &Lease) -> String {
	let host_ok = l.hostname != "*"
		&& !l.hostname.is_empty()
		&& l.hostname
			.chars()
			.all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_'));
	if host_ok {
		return l.hostname.clone();
	}
	let tail: String = l.mac.split(':').skip(3).collect::<Vec<_>>().join("");
	format!("{}-{tail}", nb.hostname_prefix)
}

/// Render the `[[node]]` TOML block for a discovered board (ssh transport).
pub fn node_block(name: &str, ip: &str) -> String {
	format!("\n[[node]]\nname = \"{name}\"\nhost = \"{ip}\"\ntransport = \"ssh\"\n")
}

/// Append `[[node]]` blocks for any discovered board whose host/IP is not already
/// present in `existing_toml`. Returns (new_toml, added_names). Idempotent by IP
/// and by name, and it APPENDS (never rewrites) so hand-authored config, comments,
/// and formatting survive.
pub fn register_into(
	nb: &Netboot,
	existing_toml: &str,
	discovered: &[Lease],
) -> (String, Vec<String>) {
	let mut out = existing_toml.to_string();
	let mut added = Vec::new();
	for l in discovered {
		let name = node_name(nb, l);
		// Skip if this IP or name is already configured (cheap textual check on
		// the quoted values - good enough for llmtune-managed fleet.toml).
		if out.contains(&format!("\"{}\"", l.ip)) || out.contains(&format!("name = \"{name}\"")) {
			continue;
		}
		if !out.ends_with('\n') && !out.is_empty() {
			out.push('\n');
		}
		out.push_str(&node_block(&name, &l.ip));
		added.push(name);
	}
	(out, added)
}

// ---------------------------------------------------------------------------
// Orchestrator (privileged IO; previews by default).
// ---------------------------------------------------------------------------

pub struct InitOpts {
	pub apply: bool,
	pub config: Option<String>,
	pub json: bool,
}

/// The `netboot init --json` payload; preview and apply share the shape
/// (`applied` says whether the files were written). Pure for the unit test.
pub fn init_json(
	applied: bool,
	dnsmasq: &str,
	exports: &str,
	unit: &str,
	port_warning: Option<&str>,
) -> serde_json::Value {
	serde_json::json!({
		"applied": applied,
		"files": [
			{"path": DNSMASQ_CONF, "content": dnsmasq},
			{"path": EXPORTS_CONF, "content": exports},
			{"path": format!("/etc/systemd/system/{HTTP_UNIT}"), "content": unit},
		],
		"next": if applied {
			"llmtune netboot up"
		} else {
			"re-run with --apply to write these files (sudo) and reload"
		},
		"port_warning": port_warning,
	})
}

fn current_user() -> String {
	std::env::var("SUDO_USER")
		.or_else(|_| std::env::var("USER"))
		.unwrap_or_else(|_| "root".into())
}

fn exe_path() -> Result<String> {
	let p = std::env::current_exe().context("resolving llmtune's own path")?;
	Ok(p.to_string_lossy().into_owned())
}

/// `netboot init`: generate the dnsmasq proxyDHCP config, the NFS export, and the
/// artifact-server unit. Preview unless `opts.apply`.
pub fn init(cfg: &crate::config::Config, opts: &InitOpts) -> Result<()> {
	let nb = require(cfg)?;
	let user = current_user();
	let exe = exe_path()?;
	let dnsmasq = dnsmasq_conf(nb);
	let exports = nfs_exports(nb);
	let unit = http_unit(&exe, &user, nb.http_port, opts.config.as_deref());
	// Advisory only - nothing binds until `netboot up` runs - but a bad
	// port is cheaper to catch here than after writing config and starting
	// services (see netboot_server::port_owner and the `up` preflight).
	let port_warning = crate::netboot_server::port_owner(nb.http_port).map(|o| {
		format!(
			"http_port {} is already in use by {} (pid {}) - the boot server \
			 will fail to bind until you change [netboot] http_port in \
			 fleet.toml or free that port",
			nb.http_port, o.comm, o.pid
		)
	});

	if !opts.apply {
		if opts.json {
			println!(
				"{}",
				init_json(false, &dnsmasq, &exports, &unit, port_warning.as_deref())
			);
			return Ok(());
		}
		println!("== {DNSMASQ_CONF} ==\n{dnsmasq}");
		println!("== {EXPORTS_CONF} ==\n{exports}");
		println!("== /etc/systemd/system/{HTTP_UNIT} ==\n{unit}");
		println!(
			"\nProxyDHCP mode: safe on a shared LAN (the router still assigns IPs).\n\
			 Ensure {tftp}/ipxe.efi, {kernel}, and {initrd} exist, then re-run with --apply.\n\
			 --apply writes the 3 files above (sudo), enables + starts dnsmasq, \
			 nfs-server, and {HTTP_UNIT}.",
			tftp = nb.tftp_root,
			kernel = nb.kernel,
			initrd = nb.initrd,
		);
		if let Some(w) = &port_warning {
			println!("\n[warn] {w}");
		}
		return Ok(());
	}

	// Preflight the artifacts so we don't stand up a boot server that hands out a
	// missing kernel.
	for (label, p) in [
		("ipxe.efi", format!("{}/ipxe.efi", nb.tftp_root)),
		("kernel", nb.kernel.clone()),
		("initrd", nb.initrd.clone()),
	] {
		if !Path::new(&p).exists() {
			bail!(
				"netboot init: {label} not found at {p} - build the image first \
				 (`netboot image build`, coming soon) or point [netboot] at existing artifacts"
			);
		}
	}

	crate::swap::sudo(&["mkdir", "-p", "/etc/dnsmasq.d", "/etc/exports.d"])?;
	crate::swap::sudo_tee(Path::new(DNSMASQ_CONF), &dnsmasq)
		.with_context(|| format!("writing {DNSMASQ_CONF}"))?;
	crate::swap::sudo_tee(Path::new(EXPORTS_CONF), &exports)
		.with_context(|| format!("writing {EXPORTS_CONF}"))?;
	crate::swap::sudo_tee(
		Path::new(&format!("/etc/systemd/system/{HTTP_UNIT}")),
		&unit,
	)
	.with_context(|| format!("writing {HTTP_UNIT}"))?;
	crate::swap::sudo(&["systemctl", "daemon-reload"])?;
	crate::swap::sudo(&["exportfs", "-ra"])?;
	if opts.json {
		println!(
			"{}",
			init_json(true, &dnsmasq, &exports, &unit, port_warning.as_deref())
		);
	} else {
		println!("[ok] wrote configs + unit. Start the stack with `llmtune netboot up`.");
		if let Some(w) = &port_warning {
			println!("[warn] {w}");
		}
	}
	Ok(())
}

const SERVICES: [&str; 3] = ["dnsmasq", "nfs-server", HTTP_UNIT];

/// `systemctl is-active` for each stack service, as (name, state) pairs. Shared
/// by `netboot status` and the cockpit's netboot view.
pub fn service_states() -> Vec<(&'static str, String)> {
	SERVICES
		.iter()
		.map(|svc| {
			let active = std::process::Command::new("systemctl")
				.args(["is-active", svc])
				.output()
				.map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
				.unwrap_or_else(|_| "unknown".into());
			(*svc, active)
		})
		.collect()
}

/// Read the lease file and filter it down to the BC-250s, then fold in the
/// kernel neighbor table (`ip -4 neigh`) for boards that got their address
/// from the LAN router instead of our dnsmasq (the default: dnsmasq off,
/// boards chainload iPXE from their ESP). Neighbor discovery needs `mac_ouis`
/// configured - it is the only identity ARP carries. Shared by
/// `netboot nodes` and the cockpit's netboot view.
pub fn discovered(nb: &Netboot) -> Vec<Lease> {
	let text = std::fs::read_to_string(&nb.leases).unwrap_or_default();
	let leased = discover(nb, &parse_leases(&text));
	let neigh_out = std::process::Command::new("ip")
		.args(["-4", "neigh", "show"])
		.output()
		.map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
		.unwrap_or_default();
	let neigh = discover_neigh(nb, &parse_neigh(&neigh_out));
	merge_discovered(leased, neigh)
}

/// Discover booted boards and append the new ones as ssh nodes to `config_path`
/// (or the default fleet.toml). Returns the node names added (empty = nothing
/// new). Non-printing, so both the CLI and the cockpit view can call it.
pub fn register_discovered(
	cfg: &crate::config::Config,
	config_path: Option<&str>,
) -> Result<Vec<String>> {
	let nb = require(cfg)?;
	let found = discovered(nb);
	if found.is_empty() {
		return Ok(vec![]);
	}
	let path = match config_path {
		Some(p) => std::path::PathBuf::from(p),
		None => crate::paths::config_file("fleet.toml")
			.ok_or_else(|| anyhow::anyhow!("no config dir for fleet.toml"))?,
	};
	// Lock the read-modify-write: two concurrent registers (CLI + the cockpit
	// view refreshing) would otherwise each read the same base and the second
	// write would drop the first one's nodes.
	let _lk = crate::paths::RmwLock::acquire(&path);
	let existing = std::fs::read_to_string(&path).unwrap_or_default();
	let (new_toml, added) = register_into(nb, &existing, &found);
	if !added.is_empty() {
		if let Some(dir) = path.parent() {
			std::fs::create_dir_all(dir).ok();
		}
		crate::paths::write_durable(&path, new_toml.as_bytes())
			.with_context(|| format!("writing {}", path.display()))?;
	}
	Ok(added)
}

/// `netboot nodes`: discover booted BC-250s from the lease file. With `register`,
/// append the new ones as ssh nodes to `config_path` (the file that was loaded,
/// so `--config` and the default location both round-trip correctly).
pub fn nodes(
	cfg: &crate::config::Config,
	register: bool,
	json: bool,
	config_path: Option<&str>,
) -> Result<()> {
	let nb = require(cfg)?;
	let found = discovered(nb);

	let added = if register && !found.is_empty() {
		register_discovered(cfg, config_path)?
	} else {
		Vec::new()
	};

	if json {
		// ONE object on stdout (never a trailing register line after the data).
		println!("{}", nodes_json(nb, &found, register, &added));
		return Ok(());
	}

	if found.is_empty() {
		println!("no BC-250 leases found in {} yet", nb.leases);
	} else {
		println!("booted BC-250s ({}):", found.len());
		for l in &found {
			println!("  {}  {}  {}", node_name(nb, l), l.ip, l.mac);
		}
	}
	if register && !found.is_empty() {
		if added.is_empty() {
			println!("[ok] all discovered boards already in fleet.toml");
		} else {
			println!(
				"[ok] registered {} node(s): {}",
				added.len(),
				added.join(", ")
			);
		}
	}
	Ok(())
}

/// The `netboot nodes --json` payload. `registered` is only meaningful when
/// `--register` was passed (`register: false` -> `registered: []`). Pure.
pub fn nodes_json(nb: &Netboot, found: &[Lease], register: bool, added: &[String]) -> String {
	let discovered: Vec<serde_json::Value> = found
		.iter()
		.map(|l| {
			serde_json::json!({
				"name": node_name(nb, l),
				"ip": l.ip,
				"mac": l.mac,
				"hostname": l.hostname,
			})
		})
		.collect();
	serde_json::json!({
		"discovered": discovered,
		"register": register,
		"registered": added,
	})
	.to_string()
}

/// `netboot serve`: the embedded artifact + iPXE HTTP server. Runs until killed;
/// systemd owns its lifecycle. Routes `/boot.ipxe` (dynamic), `/vmlinuz`,
/// `/initrd`, and `/initramfs-nfs.img` (streamed from disk). Read-only, GET only.
///
/// When an image is STAGED (`netboot image stage <id>`), the served boot.ipxe,
/// kernel, and initrd all come from that ONE image's manifest, and the initrd's
/// sha256 is re-verified against the manifest before every boot script goes
/// out: a mismatched (init=, initrd) pair yields a 500, never a boot attempt
/// that dies in stage 2. Without a staged image, the legacy NFS-root script is
/// served from the configured kernel/initrd paths.
pub fn serve(cfg: &crate::config::Config, port: u16) -> Result<()> {
	let nb = require(cfg)?.clone();
	let images_dir = std::path::PathBuf::from(&nb.images_dir);
	let addr = format!("0.0.0.0:{port}");
	let server = tiny_http::Server::http(&addr)
		.map_err(|e| anyhow::anyhow!("binding netboot server on {addr}: {e}"))?;
	match crate::netboot_image::load_active(&images_dir) {
		Ok(Some((m, _))) => println!(
			"netboot serving on http://{addr} (staged image {}, init= {})",
			m.id, m.init
		),
		Ok(None) => println!("netboot serving on http://{addr} (kernel {})", nb.kernel),
		// Startup does not die on a bad staged image (an operator may be about
		// to fix it), but every boot request will hard-fail until it is fixed.
		Err(e) => eprintln!("[fail] staged image fails verification: {e:#}"),
	}

	for req in server.incoming_requests() {
		// Only GET; strip any query string to a bare path.
		let raw = req.url().to_string();
		let path = raw.split('?').next().unwrap_or("/");
		let active = crate::netboot_image::active_id(&images_dir).is_some();
		match (req.method(), path, active) {
			(tiny_http::Method::Get, "/boot.ipxe", true) => {
				// Re-verify the pairing on EVERY boot script: the initrd we
				// are about to serve must be the one init= was built with.
				match crate::netboot_image::load_active(&images_dir) {
					Ok(Some((m, _))) => {
						let body = crate::netboot_image::boot_script(&m, &nb.http_base());
						let hdr =
							tiny_http::Header::from_bytes(&b"Content-Type"[..], &b"text/plain"[..])
								.unwrap();
						let _ =
							req.respond(tiny_http::Response::from_string(body).with_header(hdr));
					}
					Ok(None) => {
						let msg = "staged image disappeared";
						eprintln!("[fail] /boot.ipxe refused: {msg}");
						let _ = req
							.respond(tiny_http::Response::from_string(msg).with_status_code(500));
					}
					Err(e) => {
						let msg = format!("staged image failed verification: {e:#}");
						eprintln!("[fail] /boot.ipxe refused: {msg}");
						let _ = req
							.respond(tiny_http::Response::from_string(msg).with_status_code(500));
					}
				}
			}
			(tiny_http::Method::Get, "/boot.ipxe", false) => {
				let mac = raw
					.split_once("mac=")
					.map(|(_, m)| m.split('&').next().unwrap_or("").to_string());
				let body = boot_ipxe(&nb, mac.as_deref());
				let hdr = tiny_http::Header::from_bytes(&b"Content-Type"[..], &b"text/plain"[..])
					.unwrap();
				let _ = req.respond(tiny_http::Response::from_string(body).with_header(hdr));
			}
			(tiny_http::Method::Get, "/vmlinuz", true)
			| (tiny_http::Method::Get, "/initrd", true) => {
				// Artifact bytes come from the SAME staged image the script
				// was derived from (boot.ipxe above already gated the pairing).
				match staged_artifact(&images_dir, path) {
					Some(p) => serve_file(req, &p),
					None => {
						let _ = req.respond(
							tiny_http::Response::from_string("staged image unavailable")
								.with_status_code(503),
						);
					}
				}
			}
			(tiny_http::Method::Get, "/vmlinuz", false) => serve_file(req, &nb.kernel),
			(tiny_http::Method::Get, "/initramfs-nfs.img", _) => serve_file(req, &nb.initrd),
			_ => {
				let _ = req
					.respond(tiny_http::Response::from_string("not found").with_status_code(404));
			}
		}
	}
	Ok(())
}

/// The staged image's on-disk path for a served artifact route.
fn staged_artifact(images_dir: &Path, route: &str) -> Option<String> {
	let id = crate::netboot_image::active_id(images_dir)?;
	if !crate::netboot_image::valid_id(&id) {
		return None;
	}
	let file = match route {
		"/vmlinuz" => crate::netboot_image::KERNEL_FILE,
		"/initrd" => crate::netboot_image::INITRD_FILE,
		_ => return None,
	};
	Some(
		images_dir
			.join(id)
			.join(file)
			.to_string_lossy()
			.into_owned(),
	)
}

/// Stream a boot artifact from disk (kernel/initrd can be tens of MB).
fn serve_file(req: tiny_http::Request, path: &str) {
	match std::fs::File::open(path) {
		Ok(f) => {
			let _ = req.respond(tiny_http::Response::from_file(f));
		}
		Err(e) => {
			let _ = req.respond(
				tiny_http::Response::from_string(format!("artifact unavailable: {e}"))
					.with_status_code(503),
			);
		}
	}
}

// ===========================================================================
// Image pipeline (P2): build the diskless rootfs + NFS initramfs from a CachyOS
// ISO, baking in llmtune's control surface (ssh key, hostname-from-MAC, TTM, our
// binaries). The customization is a set of PURE file renderers (unit-tested);
// the orchestrator extracts/chroots/dracuts and previews by default.
// ===========================================================================

/// A file llmtune drops into the diskless rootfs. `path` is relative to the
/// rootfs; `mode` is the octal permission bits.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImageFile {
	pub path: String,
	pub content: String,
	pub mode: u32,
}

/// The TTM modprobe config: reserve `gtt_gb` GiB of unified memory for the GPU.
/// pages = gtt_gb * 1024^3 / 4096 = gtt_gb * 262144.
pub fn ttm_conf(gtt_gb: u32) -> String {
	let pages = gtt_gb * 262_144;
	format!(
		"# AUTO-GENERATED by llmtune (`netboot image build`).\n\
		 # BC-250 unified memory: {gtt_gb} GiB reserved for the GPU (GTT).\n\
		 options ttm pages_limit={pages} page_pool_size={pages}\n"
	)
}

/// The kernel cmdline baked into the NFS initramfs (dracut `--kernel-cmdline`).
pub fn dracut_cmdline(nb: &Netboot) -> String {
	format!(
		"root=nfs:{ip}:{root} ip=dhcp rd.neednet=1",
		ip = nb.server_ip,
		root = nb.rootfs,
	)
}

/// The autoboot script embedded into `ipxe.efi` (EMBED=): DHCP, then chain to
/// llmtune's HTTP boot script (falls back to the DHCP-provided filename).
pub fn ipxe_embed(nb: &Netboot) -> String {
	format!(
		"#!ipxe\ndhcp\nchain {base}/boot.ipxe || chain ${{filename}}\n",
		base = nb.http_base(),
	)
}

/// A first-boot service that names the board `<prefix>-<last-3-mac-octets>` from
/// its primary NIC, so every diskless board gets a stable, discoverable hostname
/// (llmtune registers ssh nodes by it) despite booting an identical image.
fn hostname_script(prefix: &str) -> String {
	format!(
		"#!/bin/bash\n\
		 # AUTO-GENERATED by llmtune. Name this board from its MAC on first boot.\n\
		 set -e\n\
		 iface=$(ip -o link show up | awk -F': ' '$2 !~ /^lo/ {{print $2; exit}}')\n\
		 mac=$(cat /sys/class/net/$iface/address | tr -d ':')\n\
		 hostnamectl set-hostname {prefix}-${{mac: -6}}\n"
	)
}

/// The set of files llmtune installs into the diskless rootfs. `pubkey` is the
/// verbatim SSH public key line baked into root's authorized_keys.
pub fn image_files(nb: &Netboot, pubkey: &str) -> Vec<ImageFile> {
	let f = |path: &str, content: String, mode: u32| ImageFile {
		path: path.to_string(),
		content,
		mode,
	};
	let tmpfs = |where_: &str, mode_opt: &str| {
		f(
			&format!("etc/systemd/system/{where_}.mount"),
			format!(
				"# AUTO-GENERATED by llmtune (diskless overlay).\n\
				 [Unit]\nDescription=Tmpfs overlay for /{where_}\nBefore=local-fs.target\n\n\
				 [Mount]\nWhat=tmpfs\nWhere=/{where_}\nType=tmpfs\nOptions={mode_opt},size=2G\n\n\
				 [Install]\nWantedBy=local-fs.target\n"
			),
			0o644,
		)
	};
	vec![
		// Control surface: llmtune's key + key-only root ssh.
		f(
			"root/.ssh/authorized_keys",
			format!("{}\n", pubkey.trim()),
			0o600,
		),
		f(
			"etc/ssh/sshd_config.d/10-llmtune.conf",
			"# AUTO-GENERATED by llmtune. Key-only root login for fleet control.\n\
			 PermitRootLogin prohibit-password\nPubkeyAuthentication yes\nPasswordAuthentication no\n"
				.into(),
			0o644,
		),
		// Unified-memory split for the GPU.
		f("etc/modprobe.d/ttm.conf", ttm_conf(nb.ttm_gtt_gb), 0o644),
		// Stable, discoverable hostname from the MAC.
		f(
			"usr/local/sbin/llmtune-sethostname.sh",
			hostname_script(&nb.hostname_prefix),
			0o755,
		),
		f(
			"etc/systemd/system/llmtune-sethostname.service",
			"# AUTO-GENERATED by llmtune.\n\
			 [Unit]\nDescription=Name this BC-250 from its MAC\n\
			 After=network.target\nBefore=display-manager.service\n\n\
			 [Service]\nType=oneshot\nExecStart=/usr/local/sbin/llmtune-sethostname.sh\n\
			 RemainAfterExit=yes\n\n[Install]\nWantedBy=multi-user.target\n"
				.into(),
			0o644,
		),
		// A marker the on-board tuner can read for the intended OC profile.
		f(
			"etc/llmtune-oc-profile",
			format!("{}\n", nb.oc_profile),
			0o644,
		),
		// Diskless writable overlays + home seeding.
		tmpfs("var", "mode=0755"),
		tmpfs("tmp", "mode=1777"),
		tmpfs("home", "mode=0755"),
		f(
			"usr/local/sbin/llmtune-setup-home.sh",
			"#!/bin/bash\n\
			 # AUTO-GENERATED by llmtune. Seed a home on the tmpfs /home.\n\
			 if [ ! -d /home/liveuser ]; then\n\
			 \x20 mkdir -p /home/liveuser\n\
			 \x20 cp -aT /etc/skel /home/liveuser 2>/dev/null || true\n\
			 \x20 chown -R liveuser:liveuser /home/liveuser 2>/dev/null || true\n\
			 fi\n"
				.into(),
			0o755,
		),
		f(
			"etc/systemd/system/llmtune-setup-home.service",
			"# AUTO-GENERATED by llmtune.\n\
			 [Unit]\nDescription=Seed home on the tmpfs /home\nAfter=home.mount\n\
			 Before=display-manager.service\n\n\
			 [Service]\nType=oneshot\nExecStart=/usr/local/sbin/llmtune-setup-home.sh\n\
			 RemainAfterExit=yes\n\n[Install]\nWantedBy=multi-user.target\n"
				.into(),
			0o644,
		),
	]
}

/// The systemd units the image build enables inside the chroot.
pub const IMAGE_ENABLE_UNITS: [&str; 6] = [
	"sshd",
	"NetworkManager",
	"llmtune-sethostname.service",
	"llmtune-setup-home.service",
	"var.mount",
	"tmp.mount",
];
// (home.mount is pulled in by setup-home's After=; tmp/var enabled explicitly.)

/// One step in the image build plan (for preview + execution narration).
pub struct Step {
	pub label: &'static str,
	pub detail: String,
}

/// The ordered plan `netboot image build` executes. Pure, so `--print`/preview
/// shows exactly what `--apply` will do.
pub fn image_plan(nb: &Netboot, iso: &str, pubkey_path: &str) -> Vec<Step> {
	let rootfs_stage = format!("{}/rootfs", nb.work_dir);
	let s = |label: &'static str, detail: String| Step { label, detail };
	vec![
		s(
			"extract",
			format!("unsquashfs {iso}'s airootfs.sfs -> {rootfs_stage} (skip if present)"),
		),
		s(
			"detect-kernel",
			format!("read {rootfs_stage}/usr/lib/modules/* for the kernel release"),
		),
		s(
			"customize",
			format!(
				"drop {} files into the rootfs (ssh key from {pubkey_path}, TTM {}G, \
				 hostname-from-MAC, tmpfs overlays)",
				image_files(nb, "").len(),
				nb.ttm_gtt_gb
			),
		),
		s(
			"install-binaries",
			"copy llmtune (+ arieltune if present) -> rootfs/usr/local/bin".into(),
		),
		s(
			"enable-units",
			format!("chroot systemctl enable {}", IMAGE_ENABLE_UNITS.join(" ")),
		),
		s(
			"initramfs",
			format!(
				"dracut --add 'network nfs' --kernel-cmdline '{}' -> {}",
				dracut_cmdline(nb),
				nb.initrd
			),
		),
		s(
			"deploy",
			format!(
				"kernel -> {}, initramfs -> {}, rootfs -> {} (NFS export)",
				nb.kernel, nb.initrd, nb.rootfs
			),
		),
		s(
			"ipxe",
			format!(
				"build ipxe.efi (EMBED chains {}/boot.ipxe) -> {}/ipxe.efi (skip if present)",
				nb.http_base(),
				nb.tftp_root
			),
		),
	]
}

/// Resolve the SSH public key to bake in: the configured path, else the first
/// `~/.ssh/*.pub` of the invoking user.
fn resolve_pubkey(nb: &Netboot) -> Result<(String, String)> {
	if let Some(p) = &nb.ssh_pubkey {
		let c = std::fs::read_to_string(p).with_context(|| format!("reading ssh_pubkey {p}"))?;
		return Ok((p.clone(), c));
	}
	let home = std::env::var("HOME").unwrap_or_default();
	for name in ["id_ed25519.pub", "id_rsa.pub", "id_ecdsa.pub"] {
		let p = format!("{home}/.ssh/{name}");
		if let Ok(c) = std::fs::read_to_string(&p) {
			return Ok((p, c));
		}
	}
	bail!(
		"no ssh_pubkey configured and no ~/.ssh/*.pub found - set [netboot] ssh_pubkey \
		 so llmtune can control booted boards"
	)
}

/// `netboot image build`. With `[netboot] flake` configured, the NixOS
/// co-built-triple pipeline runs (ONE nix build -> manifest-sealed image; see
/// `netboot_image`). Otherwise the legacy CachyOS ISO pipeline: extract +
/// customize + dracut. Previews by default; runs with `--apply`.
pub fn image_build(
	cfg: &crate::config::Config,
	apply: bool,
	stage: bool,
	json: bool,
) -> Result<()> {
	let nb = require(cfg)?;
	if nb.flake.is_some() {
		return crate::netboot_image::build(
			nb,
			&crate::netboot_image::BuildOpts { apply, stage, json },
		);
	}
	if stage {
		bail!(
			"--stage needs the manifest-sealed image pipeline - set [netboot] \
			 flake = \"/path/to/your/netboot-flake\" in fleet.toml (the ISO \
			 pipeline deploys in place)"
		);
	}
	let iso = nb.iso.clone().ok_or_else(|| {
		anyhow::anyhow!(
			"netboot image build needs an image source configured in fleet.toml \
			 under [netboot]: either flake = \"/path/to/your/netboot-flake\" (a \
			 NixOS flake you provide, exposing the co-built .#netbootKernel / \
			 .#netbootRamdisk / .#netbootIpxe outputs) or iso = \
			 \"/path/to/cachyos.iso\" (legacy ISO pipeline)"
		)
	})?;
	let (pubkey_path, pubkey) = resolve_pubkey(nb)?;
	let plan = image_plan(nb, &iso, &pubkey_path);

	if !apply {
		println!("netboot image build plan (work_dir {}):\n", nb.work_dir);
		for (i, st) in plan.iter().enumerate() {
			println!("  {}. [{}] {}", i + 1, st.label, st.detail);
		}
		println!("\nFiles baked into the rootfs:");
		for f in image_files(nb, &pubkey) {
			println!("  {:04o}  /{}", f.mode, f.path);
		}
		println!(
			"\nSource ISO: {iso}\nSSH key baked in: {pubkey_path}\n\
			 Re-run with --apply to execute (needs root; extracts + chroots + dracut)."
		);
		return Ok(());
	}

	image_build_apply(nb, &iso, &pubkey)
}

/// Completeness probe for an extracted airootfs tree: the directories every
/// bootable Arch-family root must have, including `var` (late in the extract
/// order) so a truncated extraction fails the probe. Returns the first
/// missing marker. Pure given a path (unit-tested on a synthetic tree).
pub(crate) fn rootfs_complete(root: &Path) -> std::result::Result<(), &'static str> {
	for marker in ["etc", "usr/bin", "usr/lib/modules", "var"] {
		if !root.join(marker).is_dir() {
			return Err(marker);
		}
	}
	Ok(())
}

/// Pick the kernel image to deploy from the extracted rootfs's /boot: the
/// CachyOS name when present (the reference image), else the first `vmlinuz-*`
/// in sorted order (a stock Arch ISO ships `vmlinuz-linux`). Pure over the
/// candidate list so the preference is unit-testable.
pub(crate) fn pick_vmlinuz(names: &[String]) -> Option<&String> {
	names
		.iter()
		.find(|n| n.as_str() == "vmlinuz-linux-cachyos")
		.or_else(|| names.iter().find(|n| n.starts_with("vmlinuz-")))
		.or_else(|| names.first())
}

/// True if `p` is safe as an `rsync --delete` target: absolute and at least
/// two path components deep. `/` would mirror-delete the whole host FS as
/// root; a top-level dir like `/srv` is almost certainly a config mistake.
pub(crate) fn safe_rsync_target(p: &str) -> bool {
	let path = Path::new(p);
	path.is_absolute()
		&& path
			.components()
			.filter(|c| matches!(c, std::path::Component::Normal(_)))
			.count()
			>= 2
}

/// The privileged executor. Split out so the plan/preview path above stays pure.
fn image_build_apply(nb: &Netboot, iso: &str, pubkey: &str) -> Result<()> {
	if std::fs::metadata(iso).is_err() {
		bail!("ISO not found: {iso}");
	}
	let sudo = |args: &[&str]| crate::swap::sudo(args);
	let work = &nb.work_dir;
	let rootfs = format!("{work}/rootfs");
	let mnt = format!("{work}/iso-mnt");

	sudo(&["mkdir", "-p", work, &mnt])?;

	// 1. Mount the ISO + extract the airootfs squashfs (idempotent). The
	// extraction is staged: unsquashfs writes into `rootfs.partial`, which is
	// renamed to `rootfs` only after a zero exit AND a completeness probe.
	// `unsquashfs -d` creates its target dir immediately, so extracting
	// straight into `rootfs` meant a Ctrl-C/OOM/disk-full mid-extract left a
	// truncated tree that every later `--apply` accepted as "already
	// extracted" - and `rsync --delete` then pushed it over the live NFS
	// export, silently un-booting the whole fleet.
	if std::fs::metadata(&rootfs).is_err() {
		let partial = format!("{work}/rootfs.partial");
		if std::fs::metadata(&partial).is_ok() {
			// Leftover from an interrupted run - never trust it, start over.
			sudo(&["rm", "-rf", "--one-file-system", &partial])?;
		}
		sudo(&["mount", "-o", "loop", iso, &mnt])?;
		let sfs = format!("{mnt}/arch/x86_64/airootfs.sfs");
		let r = sudo(&["unsquashfs", "-d", &partial, &sfs]);
		let _ = sudo(&["umount", &mnt]);
		r.context("extracting airootfs.sfs")?;
		if let Err(missing) = rootfs_complete(Path::new(&partial)) {
			bail!(
				"extracted rootfs at {partial} is incomplete (`{missing}` is \
				 missing) - unsquashfs exited 0 but the tree is not a bootable \
				 root; refusing to stage it. Check disk space and the ISO, \
				 then re-run."
			);
		}
		sudo(&["mv", "-T", &partial, &rootfs])?;
	} else if let Err(missing) = rootfs_complete(Path::new(&rootfs)) {
		// A pre-staging llmtune (or a hand-made tree) could have left a
		// truncated rootfs here; deploying it would replace the live export.
		bail!(
			"existing rootfs at {rootfs} is incomplete (`{missing}` is \
			 missing) - likely an interrupted extraction from an earlier run. \
			 Remove it (sudo rm -rf {rootfs}) and re-run to re-extract."
		);
	} else {
		println!("[ok] rootfs already extracted (verified) at {rootfs}");
	}

	// 2. Detect the kernel release from the extracted modules.
	let modules = format!("{rootfs}/usr/lib/modules");
	let kver = std::fs::read_dir(&modules)
		.with_context(|| format!("reading {modules}"))?
		.flatten()
		.find_map(|e| {
			let n = e.file_name().to_string_lossy().into_owned();
			e.path().join("kernel").is_dir().then_some(n)
		})
		.ok_or_else(|| anyhow::anyhow!("no kernel modules found under {modules}"))?;
	println!("[ok] kernel release: {kver}");

	// 3. Drop the customization files.
	for file in image_files(nb, pubkey) {
		let dst = format!("{rootfs}/{}", file.path);
		if let Some(dir) = Path::new(&dst).parent() {
			sudo(&["mkdir", "-p", &dir.to_string_lossy()])?;
		}
		crate::swap::sudo_tee(Path::new(&dst), &file.content)
			.with_context(|| format!("writing {dst}"))?;
		sudo(&["chmod", &format!("{:o}", file.mode), &dst])?;
	}
	println!("[ok] customization files installed");

	// 4. Copy our binaries in (best-effort; arieltune may be absent).
	if let Ok(exe) = std::env::current_exe() {
		let _ = sudo(&[
			"cp",
			&exe.to_string_lossy(),
			&format!("{rootfs}/usr/local/bin/llmtune"),
		]);
	}
	if Path::new("/usr/local/bin/arieltune").exists() {
		let _ = sudo(&[
			"cp",
			"/usr/local/bin/arieltune",
			&format!("{rootfs}/usr/local/bin/arieltune"),
		]);
	}

	// 5. Enable units inside the chroot.
	let mut enable = vec!["systemctl", "enable"];
	enable.extend(IMAGE_ENABLE_UNITS.iter());
	let mut chroot_enable = vec!["chroot", &rootfs];
	chroot_enable.extend(enable.iter());
	sudo(&chroot_enable)?;

	// 6. Build the NFS initramfs in the chroot.
	let cmdline = dracut_cmdline(nb);
	sudo(&[
		"chroot",
		&rootfs,
		"dracut",
		"--force",
		"--add",
		"network nfs",
		"--install",
		"/etc/modprobe.d/ttm.conf",
		"--kernel-cmdline",
		&cmdline,
		"/boot/initramfs-nfs.img",
		&kver,
	])
	.context("building NFS initramfs")?;

	// 7. Deploy kernel + initramfs to the served paths and the rootfs to NFS.
	sudo(&[
		"mkdir",
		"-p",
		&parent_of(&nb.kernel),
		&parent_of(&nb.initrd),
		&nb.rootfs,
	])?;
	sudo(&[
		"cp",
		&format!("{rootfs}/boot/initramfs-nfs.img"),
		&nb.initrd,
	])?;
	// The kernel image name varies by distro spin (vmlinuz-linux-cachyos,
	// vmlinuz-linux, vmlinuz-6.x...): glob rather than hardcode one spin's name.
	let boot_dir = format!("{rootfs}/boot");
	let mut kernels: Vec<String> = std::fs::read_dir(&boot_dir)
		.with_context(|| format!("reading {boot_dir}"))?
		.flatten()
		.filter_map(|e| {
			let n = e.file_name().to_string_lossy().into_owned();
			(n.starts_with("vmlinuz") && e.path().is_file()).then_some(n)
		})
		.collect();
	kernels.sort();
	let vmlinuz_name = pick_vmlinuz(&kernels)
		.ok_or_else(|| anyhow::anyhow!("no vmlinuz-* kernel image found under {boot_dir}"))?;
	sudo(&["cp", &format!("{boot_dir}/{vmlinuz_name}"), &nb.kernel])?;
	// Guard the mirror-with-delete target: `rootfs = "/"` (or a bare top-level
	// dir) in a pasted config would otherwise rsync-delete the host FS as root.
	if !safe_rsync_target(&nb.rootfs) {
		bail!(
			"refusing `rsync --delete` onto '{}': the netboot rootfs export must \
			 be a dedicated directory at least two levels deep (e.g. /srv/nfs/bc250-root)",
			nb.rootfs
		);
	}
	sudo(&[
		"rsync",
		"-aHAX",
		"--delete",
		&format!("{rootfs}/"),
		&format!("{}/", nb.rootfs),
	])
	.context("deploying rootfs to the NFS export")?;
	sudo(&["exportfs", "-ra"])?;

	// 8. Build ipxe.efi (embedding a chain to llmtune's boot script) if absent.
	build_ipxe(nb)?;

	println!(
		"[ok] image built + deployed. Start the stack with `netboot up` \
		 (server {}).",
		nb.http_base()
	);
	Ok(())
}

/// Build `ipxe.efi` with an embedded autoboot that chains llmtune's HTTP boot
/// script, and place it in the TFTP root. Skips if already present (the build
/// needs the upstream iPXE tree + a toolchain, so it is done once).
fn build_ipxe(nb: &Netboot) -> Result<()> {
	let efi = format!("{}/ipxe.efi", nb.tftp_root);
	if Path::new(&efi).exists() {
		println!("[ok] {efi} already present");
		return Ok(());
	}
	let sudo = |args: &[&str]| crate::swap::sudo(args);
	let src = format!("{}/ipxe", nb.work_dir);
	if !Path::new(&src).exists() {
		sudo(&[
			"git",
			"clone",
			"--depth=1",
			"https://github.com/ipxe/ipxe.git",
			&src,
		])
		.context("cloning iPXE")?;
	}
	let embed = format!("{src}/src/llmtune-autoboot.ipxe");
	crate::swap::sudo_tee(Path::new(&embed), &ipxe_embed(nb))
		.with_context(|| format!("writing {embed}"))?;
	sudo(&[
		"make",
		"-C",
		&format!("{src}/src"),
		"bin-x86_64-efi/ipxe.efi",
		"EMBED=llmtune-autoboot.ipxe",
	])
	.context("building ipxe.efi (needs build-essential + liblzma)")?;
	sudo(&["mkdir", "-p", &nb.tftp_root])?;
	sudo(&["cp", &format!("{src}/src/bin-x86_64-efi/ipxe.efi"), &efi])?;
	println!("[ok] built {efi}");
	Ok(())
}

fn parent_of(p: &str) -> String {
	Path::new(p)
		.parent()
		.map(|d| d.to_string_lossy().into_owned())
		.unwrap_or_else(|| "/".into())
}

/// `netboot image stage <id>`: verify the image's manifest (initrd sha256 +
/// init= pairing) and make it the served one. Any mismatch refuses and leaves
/// the previous staging in place.
pub fn image_stage(cfg: &crate::config::Config, id: &str, json: bool) -> Result<()> {
	let nb = require(cfg)?;
	let m = crate::netboot_image::stage(Path::new(&nb.images_dir), id)?;
	if json {
		println!(
			"{}",
			serde_json::json!({
				"staged": m.id,
				"init": m.init,
				"initrd_sha256": m.initrd.sha256,
			})
		);
	} else {
		println!("[ok] staged image {} (verified; init= {})", m.id, m.init);
	}
	Ok(())
}

/// `netboot image list`: sealed images with their manifests (the staged one is
/// marked) plus the legacy ISO-pipeline artifacts.
pub fn image_list(cfg: &crate::config::Config, json: bool) -> Result<()> {
	let nb = require(cfg)?;
	let images_dir = Path::new(&nb.images_dir);
	let images = crate::netboot_image::list(images_dir);
	let active = crate::netboot_image::active_id(images_dir);

	let rootfs_stage = format!("{}/rootfs", nb.work_dir);
	let checks = [
		("iso", nb.iso.clone().unwrap_or_default()),
		("rootfs_stage", rootfs_stage),
		("nfs_root", nb.rootfs.clone()),
		("kernel", nb.kernel.clone()),
		("initrd", nb.initrd.clone()),
		("ipxe_efi", format!("{}/ipxe.efi", nb.tftp_root)),
	];
	if json {
		let imgs: Vec<serde_json::Value> = images
			.iter()
			.map(|(m, dir)| {
				serde_json::json!({
					"id": m.id,
					"built_at": crate::fmt::fmt_ts(m.built_at_unix),
					"init": m.init,
					"kernel_sha256": m.kernel.sha256,
					"initrd_sha256": m.initrd.sha256,
					"dir": dir.display().to_string(),
					"active": active.as_deref() == Some(m.id.as_str()),
				})
			})
			.collect();
		let arts: Vec<serde_json::Value> = checks
			.iter()
			.map(|(k, p)| {
				serde_json::json!({
					"what": k,
					"path": p,
					"present": !p.is_empty() && Path::new(p).exists(),
				})
			})
			.collect();
		println!(
			"{}",
			serde_json::json!({"images": imgs, "active": active, "artifacts": arts})
		);
	} else {
		if images.is_empty() {
			println!("no sealed images under {} yet", images_dir.display());
		} else {
			println!("sealed images ({}):", images_dir.display());
			for (m, _) in &images {
				let mark = if active.as_deref() == Some(m.id.as_str()) {
					"[active]"
				} else {
					"        "
				};
				println!(
					"  {mark} {}  {}  initrd sha {}\n           init= {}",
					m.id,
					crate::fmt::fmt_ts(m.built_at_unix),
					&m.initrd.sha256[..12.min(m.initrd.sha256.len())],
					m.init
				);
			}
		}
		println!("legacy artifacts:");
		for (k, p) in &checks {
			let present = !p.is_empty() && Path::new(p).exists();
			let mark = if present { "[ok]  " } else { "[--]  " };
			println!("  {mark} {k}: {}", if p.is_empty() { "(unset)" } else { p });
		}
	}
	Ok(())
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::config::Config;

	fn nb() -> Netboot {
		let toml = "[netboot]\n\
					interface = \"enp6s0\"\n\
					server_ip = \"192.168.1.91\"\n\
					subnet = \"192.168.1.0\"\n";
		Config::load_str(toml).unwrap().netboot.unwrap()
	}

	#[test]
	fn pick_vmlinuz_prefers_cachyos_then_any_vmlinuz() {
		let names = |v: &[&str]| v.iter().map(|s| s.to_string()).collect::<Vec<_>>();
		// The reference spin wins when present.
		let ks = names(&["vmlinuz-linux", "vmlinuz-linux-cachyos"]);
		assert_eq!(pick_vmlinuz(&ks).unwrap(), "vmlinuz-linux-cachyos");
		// A stock Arch ISO: vmlinuz-linux is fine.
		let ks = names(&["vmlinuz-linux"]);
		assert_eq!(pick_vmlinuz(&ks).unwrap(), "vmlinuz-linux");
		// Sorted-first deterministic pick among several.
		let ks = names(&["vmlinuz-6.9-generic", "vmlinuz-linux-lts"]);
		assert_eq!(pick_vmlinuz(&ks).unwrap(), "vmlinuz-6.9-generic");
		assert!(pick_vmlinuz(&[]).is_none());
	}

	#[test]
	fn rsync_target_guard_rejects_root_and_top_level() {
		// The failure this guard exists for: rootfs = "/" would
		// mirror-with-delete the host filesystem as root.
		assert!(!safe_rsync_target("/"));
		assert!(!safe_rsync_target("/srv"));
		assert!(!safe_rsync_target("relative/path"));
		assert!(!safe_rsync_target(""));
		// Real export locations pass.
		assert!(safe_rsync_target("/srv/nfs/bc250-root"));
		assert!(safe_rsync_target("/srv/nfs"));
		assert!(safe_rsync_target("/var/lib/llmtune/root"));
	}

	#[test]
	fn image_build_without_an_image_source_errors_actionably() {
		// No [netboot] flake and no iso: the error must point the operator at
		// the config (bring-your-own image source), name BOTH options, and
		// never reference a private path.
		let cfg = Config::load_str(
			"[netboot]\n\
			 interface = \"enp6s0\"\n\
			 server_ip = \"192.168.1.91\"\n\
			 subnet = \"192.168.1.0\"\n",
		)
		.unwrap();
		let err = image_build(&cfg, false, false, false)
			.unwrap_err()
			.to_string();
		assert!(err.contains("[netboot]"), "points at the section: {err}");
		assert!(err.contains("fleet.toml"), "points at the config: {err}");
		assert!(
			err.contains("flake") && err.contains("iso"),
			"names both image sources: {err}"
		);
		assert!(
			err.contains(".#netbootKernel"),
			"documents the flake output contract: {err}"
		);
		assert!(
			!err.contains("bc250-nixos") && !err.contains("/tank"),
			"no private/internal paths in the error: {err}"
		);

		// --stage without the flake pipeline refuses with the same pointer.
		let err = image_build(&cfg, false, true, false)
			.unwrap_err()
			.to_string();
		assert!(err.contains("flake") && err.contains("fleet.toml"), "{err}");
		assert!(
			!err.contains("bc250-nixos") && !err.contains("/tank"),
			"{err}"
		);
	}

	#[test]
	fn init_json_shape_carries_all_three_files() {
		let v = init_json(false, "dns cfg", "exp cfg", "unit cfg", None);
		assert_eq!(v["applied"], serde_json::Value::Bool(false));
		let files = v["files"].as_array().unwrap();
		assert_eq!(files.len(), 3);
		assert_eq!(files[0]["path"], DNSMASQ_CONF);
		assert_eq!(files[0]["content"], "dns cfg");
		assert_eq!(files[1]["path"], EXPORTS_CONF);
		assert!(files[2]["path"]
			.as_str()
			.unwrap()
			.ends_with(&format!("/{HTTP_UNIT}")));
		assert!(v["next"].as_str().unwrap().contains("--apply"));
		assert!(v["port_warning"].is_null());
		let v = init_json(true, "a", "b", "c", Some("http_port 8090 is busy"));
		assert_eq!(v["applied"], serde_json::Value::Bool(true));
		assert!(v["next"].as_str().unwrap().contains("netboot up"));
		assert_eq!(v["port_warning"], "http_port 8090 is busy");
	}

	#[test]
	fn nodes_json_is_one_object_and_escapes_fields() {
		let found = vec![Lease {
			mac: "58:11:22:aa:bb:cc".into(),
			ip: "198.51.100.223".into(),
			// hostile hostname must be escaped, not string-formatted
			hostname: "bc\"250\\evil".into(),
			expiry: 1,
		}];
		let s = nodes_json(&nb(), &found, true, &["bc250-aabbcc".to_string()]);
		let v: serde_json::Value = serde_json::from_str(&s).expect("valid JSON");
		assert_eq!(v["discovered"][0]["ip"], "198.51.100.223");
		assert_eq!(v["discovered"][0]["hostname"], "bc\"250\\evil");
		assert_eq!(v["register"], serde_json::Value::Bool(true));
		assert_eq!(v["registered"][0], "bc250-aabbcc");
		// no boards, no register: still the same object shape
		let s = nodes_json(&nb(), &[], false, &[]);
		let v: serde_json::Value = serde_json::from_str(&s).unwrap();
		assert_eq!(v["discovered"].as_array().unwrap().len(), 0);
		assert_eq!(v["registered"].as_array().unwrap().len(), 0);
	}

	#[test]
	fn dnsmasq_is_proxy_mode_and_chains_ipxe() {
		let c = dnsmasq_conf(&nb());
		assert!(
			c.contains("dhcp-range=192.168.1.0,proxy"),
			"must be proxyDHCP"
		);
		assert!(c.contains("interface=enp6s0") && c.contains("bind-interfaces"));
		// stage 1 TFTP NBP + stage 2 HTTP chain
		assert!(c.contains("dhcp-boot=tag:efi64,tag:!ipxe,ipxe.efi,,192.168.1.91"));
		assert!(c.contains("dhcp-boot=tag:ipxe,http://192.168.1.91:8090/boot.ipxe"));
		assert!(c.contains("enable-tftp") && c.contains("tftp-root=/srv/tftp"));
	}

	#[test]
	fn exports_line_uses_cidr_and_readonly() {
		let e = nfs_exports(&nb());
		assert!(e.contains("/srv/nfs/bc250-root 192.168.1.0/24(ro,"));
	}

	#[test]
	fn boot_script_points_at_nfs_root_and_oc_profile() {
		let s = boot_ipxe(&nb(), None);
		assert!(s.starts_with("#!ipxe"));
		assert!(s.contains("kernel http://192.168.1.91:8090/vmlinuz"));
		assert!(s.contains("root=nfs:192.168.1.91:/srv/nfs/bc250-root"));
		assert!(s.contains("llmtune.oc=balanced"));
		assert!(s.contains("initrd http://192.168.1.91:8090/initramfs-nfs.img"));
	}

	#[test]
	fn http_unit_execstart_names_serve() {
		let u = http_unit("/usr/local/bin/llmtune", "cache", 8090, None);
		assert!(u.contains("ExecStart=/usr/local/bin/llmtune netboot serve --port 8090"));
		assert!(u.contains("User=cache"));
	}

	#[test]
	fn leases_parse_and_filter_by_hostname() {
		let text = "1783300000 58:11:22:aa:bb:cc 192.168.1.120 bc250-01 *\n\
					1783300001 aa:bb:cc:dd:ee:ff 192.168.1.50 my-laptop *\n\
					garbage line\n\
					1783300002 58:11:22:aa:bb:c1 192.168.1.121 bc250-02 01:58\n";
		let leases = parse_leases(text);
		assert_eq!(leases.len(), 3, "3 well-formed leases, 1 garbage skipped");
		let found = discover(&nb(), &leases);
		assert_eq!(found.len(), 2, "only the two bc250-* hosts");
		assert!(found.iter().all(|l| l.hostname.starts_with("bc250")));
	}

	#[test]
	fn leases_require_a_literal_ipv4_address() {
		// The lease file is attacker-influenced and the IP becomes an ssh
		// target - anything that is not a literal IPv4 address is dropped
		// (defense in depth on top of the argv `--` guard).
		let text = "1 58:11:22:aa:bb:cc -oProxyCommand=evil bc250-01 *\n\
					1 58:11:22:aa:bb:c1 evil.example bc250-02 *\n\
					1 58:11:22:aa:bb:c2 192.168.1.300 bc250-03 *\n\
					1 58:11:22:aa:bb:c3 192.168.1.121 bc250-04 *\n";
		let leases = parse_leases(text);
		assert_eq!(leases.len(), 1, "only the literal IPv4 lease survives");
		assert_eq!(leases[0].ip, "192.168.1.121");
	}

	#[test]
	fn rootfs_completeness_probe_catches_truncation() {
		// A truncated extraction (missing late-order markers) must fail the
		// probe; a full marker set passes.
		let base = std::env::temp_dir().join(format!("llmtune-rootfs-{}", std::process::id()));
		let _ = std::fs::remove_dir_all(&base);
		std::fs::create_dir_all(&base).unwrap();
		// empty tree -> first marker missing
		assert_eq!(rootfs_complete(&base), Err("etc"));
		// partial tree (interrupted mid-usr) -> a later marker missing
		std::fs::create_dir_all(base.join("etc")).unwrap();
		std::fs::create_dir_all(base.join("usr/bin")).unwrap();
		assert_eq!(rootfs_complete(&base), Err("usr/lib/modules"));
		// full marker set -> complete
		std::fs::create_dir_all(base.join("usr/lib/modules")).unwrap();
		std::fs::create_dir_all(base.join("var")).unwrap();
		assert_eq!(rootfs_complete(&base), Ok(()));
		// a FILE where a dir belongs does not count
		std::fs::remove_dir_all(base.join("var")).unwrap();
		std::fs::write(base.join("var"), b"not a dir").unwrap();
		assert_eq!(rootfs_complete(&base), Err("var"));
		let _ = std::fs::remove_dir_all(&base);
	}

	#[test]
	fn discover_by_mac_oui_when_configured() {
		let toml = "[netboot]\n\
					interface = \"enp6s0\"\n\
					server_ip = \"192.168.1.91\"\n\
					subnet = \"192.168.1.0\"\n\
					mac_ouis = [\"58:11:22\"]\n";
		let n = Config::load_str(toml).unwrap().netboot.unwrap();
		let leases = parse_leases(
			"1 58:11:22:00:00:01 192.168.1.120 * *\n1 aa:bb:cc:00:00:02 192.168.1.50 host *\n",
		);
		let found = discover(&n, &leases);
		assert_eq!(found.len(), 1);
		assert_eq!(found[0].ip, "192.168.1.120");
	}

	#[test]
	fn register_appends_only_new_nodes_and_preserves_existing() {
		let n = nb();
		let existing = "# my fleet\n[[node]]\nname = \"bc250-01\"\nhost = \"192.168.1.120\"\ntransport = \"ssh\"\n";
		let leases = parse_leases(
			"1 58:11:22:00:00:01 192.168.1.120 bc250-01 *\n\
			 1 58:11:22:00:00:02 192.168.1.121 bc250-02 *\n",
		);
		let found = discover(&n, &leases);
		let (out, added) = register_into(&n, existing, &found);
		assert_eq!(added, vec!["bc250-02".to_string()], "only the new board");
		assert!(out.contains("# my fleet"), "comment preserved");
		assert_eq!(
			out.matches("192.168.1.120").count(),
			1,
			"no dup for existing"
		);
		assert!(out.contains("host = \"192.168.1.121\""));
		// The appended block must itself parse as a valid node.
		let cfg = Config::load_str(&out).unwrap();
		assert!(cfg.node("bc250-02").is_some());
	}

	#[test]
	fn ttm_conf_computes_pages_from_gib() {
		// 12 GiB -> 12 * 262144 = 3145728 pages (the script's magic number).
		assert!(ttm_conf(12).contains("pages_limit=3145728 page_pool_size=3145728"));
		assert!(ttm_conf(8).contains("pages_limit=2097152"));
	}

	#[test]
	fn dracut_cmdline_is_nfs_root() {
		assert_eq!(
			dracut_cmdline(&nb()),
			"root=nfs:192.168.1.91:/srv/nfs/bc250-root ip=dhcp rd.neednet=1"
		);
	}

	#[test]
	fn ipxe_embed_chains_the_server_script() {
		let e = ipxe_embed(&nb());
		assert!(e.starts_with("#!ipxe"));
		assert!(e.contains("chain http://192.168.1.91:8090/boot.ipxe"));
	}

	#[test]
	fn image_files_bake_key_hostname_and_ttm() {
		let files = image_files(&nb(), "ssh-ed25519 AAAAKEY user@host");
		let by = |p: &str| files.iter().find(|f| f.path == p).expect(p);
		// ssh key -> root authorized_keys, 0600
		let ak = by("root/.ssh/authorized_keys");
		assert!(ak.content.contains("ssh-ed25519 AAAAKEY"));
		assert_eq!(ak.mode, 0o600);
		// key-only root login
		assert!(by("etc/ssh/sshd_config.d/10-llmtune.conf")
			.content
			.contains("PermitRootLogin prohibit-password"));
		// TTM split present
		assert!(by("etc/modprobe.d/ttm.conf")
			.content
			.contains("pages_limit=3145728"));
		// hostname-from-MAC service + script, executable
		let hs = by("usr/local/sbin/llmtune-sethostname.sh");
		assert_eq!(hs.mode, 0o755);
		assert!(hs.content.contains("hostnamectl set-hostname bc250-"));
		assert!(files
			.iter()
			.any(|f| f.path == "etc/systemd/system/llmtune-sethostname.service"));
		// diskless tmpfs overlays
		for m in ["var", "tmp", "home"] {
			assert!(files
				.iter()
				.any(|f| f.path == format!("etc/systemd/system/{m}.mount")));
		}
	}

	#[test]
	fn image_plan_covers_the_pipeline() {
		let p = image_plan(&nb(), "/srv/cachyos.iso", "/home/u/.ssh/id_ed25519.pub");
		let labels: Vec<_> = p.iter().map(|s| s.label).collect();
		assert_eq!(
			labels,
			vec![
				"extract",
				"detect-kernel",
				"customize",
				"install-binaries",
				"enable-units",
				"initramfs",
				"deploy",
				"ipxe",
			]
		);
	}

	#[test]
	fn neigh_parse_skips_failed_and_non_mac() {
		let text = "198.51.100.223 dev enp2s0f0np0 lladdr 00:00:5e:00:53:63 REACHABLE \n\
					192.168.1.119 dev enp2s0f0np0 FAILED \n\
					fe80::1 dev enp2s0f0np0 lladdr 00:00:5e:00:00:01 STALE \n\
					192.168.1.40 dev enp2s0f0np0 lladdr 00:00:5e:00:53:94 STALE \n";
		let pairs = parse_neigh(text);
		assert_eq!(
			pairs,
			vec![
				("198.51.100.223".to_string(), "00:00:5e:00:53:63".to_string()),
				("192.168.1.40".to_string(), "00:00:5e:00:53:94".to_string()),
			],
			"FAILED (no lladdr) and non-IPv4 entries skipped"
		);
	}

	#[test]
	fn neigh_discovery_requires_mac_ouis() {
		let pairs = vec![("198.51.100.223".to_string(), "00:00:5e:00:53:63".to_string())];
		// Without mac_ouis ARP carries no identity: discover nothing rather
		// than register every LAN device.
		assert!(discover_neigh(&nb(), &pairs).is_empty());
		let toml = "[netboot]\n\
					interface = \"enp6s0\"\n\
					server_ip = \"198.51.100.225\"\n\
					subnet = \"198.51.100.0\"\n\
					mac_ouis = [\"00:00:5e\"]\n";
		let n = Config::load_str(toml).unwrap().netboot.unwrap();
		let found = discover_neigh(&n, &pairs);
		assert_eq!(found.len(), 1);
		assert_eq!(found[0].ip, "198.51.100.223");
		assert_eq!(found[0].hostname, "*");
		// and the fallback name is bc250-<last-3-octets>
		assert_eq!(node_name(&n, &found[0]), "bc250-005363");
	}

	#[test]
	fn merge_discovered_dedups_by_mac_lease_wins() {
		let lease = Lease {
			mac: "00:00:5e:00:53:63".into(),
			ip: "198.51.100.223".into(),
			hostname: "bc250-005363".into(),
			expiry: 9,
		};
		let neigh_same = Lease {
			mac: "00:00:5e:00:53:63".into(),
			ip: "198.51.100.223".into(),
			hostname: "*".into(),
			expiry: 0,
		};
		let neigh_new = Lease {
			mac: "00:00:5e:00:00:02".into(),
			ip: "192.168.1.224".into(),
			hostname: "*".into(),
			expiry: 0,
		};
		let merged = merge_discovered(vec![lease.clone()], vec![neigh_same, neigh_new.clone()]);
		assert_eq!(merged.len(), 2);
		assert_eq!(merged[0], lease, "lease (with hostname) wins the dup");
		assert_eq!(merged[1], neigh_new);
		// register_into over the merged set stays idempotent
		let n = nb();
		let (out, added) = register_into(&n, "", &merged);
		assert_eq!(added.len(), 2);
		let (out2, added2) = register_into(&n, &out, &merged);
		assert!(added2.is_empty(), "second register adds nothing");
		assert_eq!(out, out2);
	}

	#[test]
	fn node_name_falls_back_to_mac_tail() {
		let n = nb();
		let l = Lease {
			mac: "58:11:22:aa:bb:cc".into(),
			ip: "192.168.1.9".into(),
			hostname: "*".into(),
			expiry: 0,
		};
		assert_eq!(node_name(&n, &l), "bc250-aabbcc");
	}
}
