// SPDX-License-Identifier: GPL-2.0-only
//! First-run setup - from a bare box to serving-ready without hand-editing TOML.
//!
//! llmtune's swap layers a systemd drop-in onto a base `llama-server` unit; on a
//! fresh box that unit does not exist yet. `setup` generates it (plus a starter
//! `fleet.toml` and the models dir), runs a preflight, and points at the next
//! step (`build install vulkan`). The unit/config GENERATORS are pure functions
//! (unit-tested); the orchestrator does the IO and is exercised via `--print`.

use crate::config::{Config, Node};
use crate::{build, doctor, swap};
use anyhow::{bail, Context, Result};
use std::io::Write;
use std::path::{Path, PathBuf};

/// Options for a setup run.
pub struct Opts {
	/// Show the plan + generated files, write nothing.
	pub print: bool,
	/// Don't prompt - apply every step.
	pub assume_yes: bool,
	/// User the llama service runs as (default: the invoking user).
	pub user: Option<String>,
	/// Override the models directory (default: the node's configured dir).
	pub models_dir: Option<String>,
}

/// The base llama-server systemd unit. llmtune's per-model drop-in overrides
/// `ExecStart`/`Environment` at load time, so the base `ExecStart` is a dormant
/// placeholder; `Restart=always` gives crash recovery once a model is serving
/// (e.g. an MTP draft crash restarts the server). The unit is written but not
/// started - the first `node load` stages a drop-in and starts it.
pub fn unit_text(user: &str) -> String {
	format!(
		"# AUTO-GENERATED by llmtune (`llmtune setup`). This is the BASE unit;\n\
		 # llmtune's per-model drop-in overrides ExecStart/Environment when you\n\
		 # load a model. Do not `systemctl start` it directly with no model loaded.\n\
		 [Unit]\n\
		 Description=llama.cpp server (managed by llmtune)\n\
		 After=network-online.target\n\
		 Wants=network-online.target\n\
		 # Crash-loop guard: a model that fails to load must NOT restart forever -\n\
		 # on this silicon a rapid Vulkan-init storm wedges the GPU. Give up after\n\
		 # 4 failures in 120s; `node load` resets this before staging a new model.\n\
		 StartLimitIntervalSec=120\n\
		 StartLimitBurst=4\n\
		 \n\
		 [Service]\n\
		 Type=simple\n\
		 User={user}\n\
		 # placeholder; llmtune's drop-in supplies the real bin/model/flags\n\
		 ExecStart=/bin/false\n\
		 Restart=always\n\
		 RestartSec=5\n\
		 # GPU/DRM access for the Vulkan backend\n\
		 SupplementaryGroups=video render\n\
		 \n\
		 [Install]\n\
		 WantedBy=multi-user.target\n"
	)
}
/// OpenRC init script template for llama-server.
/// command="/bin/false" is a systemd-legacy placeholder - llmtune's per-model
/// swap overwrites it via /etc/conf.d/llama-server (command="<real-path>").
/// output/input redirect stdout/stderr to /var/log/openrc/llama-server.log.
pub fn openrc_init_text(user: &str) -> String {
	format!(
		"#!/sbin/openrc-run\n\
		 # AUTO-GENERATED by llmtune (`llmtune setup`). OpenRC service for llama-server.\n\
		 description=\"llama.cpp server (managed by llmtune)\"\n\
		 command=\"/bin/false\"\n\
		 command_user=\"{user}\"\n\
		 supervisor=\"supervise-daemon\"\n\
		 output=\"/var/log/openrc/llama-server.log\"\n\
		 input=\"/dev/null\"\n\
		 \n\
		 depend() {{\n\
		 \tafter net\n\
		 }}\n"
	)
}

/// OpenRC conf template for llama-server.
pub fn openrc_conf_text(user: &str) -> String {
	format!(
		"# AUTO-GENERATED by llmtune (`llmtune setup`). OpenRC conf for llama-server.\n\
		 RC_USER=\"{user}\"\n"
	)
}

/// A low-sort drop-in that neutralizes the base unit's `ExecStart` to a safe
/// no-op. It sorts before llmtune's per-model drop-in, so when a model is
/// loaded the model wins; when nothing is loaded (or the model drop-in is
/// cleared) the effective `ExecStart` is `/bin/false` - a clean exit instead of
/// crash-looping whatever stale/broken binary the base unit named. This makes an
/// unmanaged or pre-existing messy unit bulletproof without editing it.
pub const SAFE_FALLBACK_DROPIN: &str = "\
# AUTO-GENERATED by llmtune. Safe fallback: an unloaded/cleared state no-ops\n\
# instead of crash-looping a stale ExecStart. llmtune's per-model drop-in\n\
# sorts later and overrides this when you load a model. Do not edit.\n\
[Service]\n\
ExecStart=\n\
ExecStart=/bin/false\n";

/// Crash-loop guard drop-in - caps restarts so a model that fails to load can't
/// storm Vulkan init and wedge the GPU. Applied even to a pre-existing base unit.
pub const LIMITS_DROPIN: &str = "\
# AUTO-GENERATED by llmtune. Crash-loop guard: give up after 4 failed starts\n\
# in 120s (a rapid Vulkan-init storm wedges this GPU). Do not edit.\n\
[Unit]\n\
StartLimitIntervalSec=120\n\
StartLimitBurst=4\n\
[Service]\n\
RestartSec=5\n";

/// A starter `fleet.toml` for the local node (defaults only; a single BC-250
/// never needs an explicit [[node]] block).
pub fn fleet_toml(models_dir: &str, llama_unit: &str, llama_url: &str) -> String {
	format!(
		"# llmtune fleet config (generated by `llmtune setup`).\n\
		 # A single local BC-250 needs only these defaults; add [[node]] blocks to\n\
		 # control other boxes, and [[cluster]] blocks to pool them. See SPEC.md 4.3.\n\
		 \n\
		 [defaults]\n\
		 models_dir = \"{models_dir}\"\n\
		 llama_unit = \"{llama_unit}\"\n\
		 llama_url  = \"{llama_url}\"\n"
	)
}

/// The invoking user - the real user even under `sudo` (SUDO_USER), else $USER.
fn current_user() -> String {
	std::env::var("SUDO_USER")
		.or_else(|_| std::env::var("USER"))
		.unwrap_or_else(|_| "root".to_string())
}

/// Where an existing unit named `unit` lives, if any (so setup never clobbers a
/// hand-written or vendor unit). Supports systemd units and OpenRC init/conf.
pub(crate) fn existing_unit(unit: &str) -> Option<PathBuf> {
	let service_name = unit.strip_suffix(".service").unwrap_or(unit);
	let paths = vec![
		crate::platform::user_unit_dir(),
		PathBuf::from("/etc/systemd/system"),
		PathBuf::from("/run/systemd/system"),
		PathBuf::from("/usr/lib/systemd/system"),
		PathBuf::from("/lib/systemd/system"),
		PathBuf::from("/etc/init.d"),
		PathBuf::from("/etc/conf.d"),
	];
	paths
		.into_iter()
		.map(|b| {
			if b.ends_with("init.d") {
				b.join(service_name)
			} else {
				b.join(unit)
			}
		})
		.find(|p| p.exists())
}

fn fleet_path() -> Option<PathBuf> {
	crate::paths::config_file("fleet.toml")
}

fn confirm(prompt: &str, assume_yes: bool) -> bool {
	use std::io::IsTerminal;
	if assume_yes {
		println!("{prompt} [y]");
		return true;
	}
	if !std::io::stdin().is_terminal() {
		// Non-interactive caller without --yes: never hang on a prompt;
		// skip the step and say why (`setup --yes` is the escape hatch).
		println!("{prompt} [skipped: no tty - pass --yes to apply non-interactively]");
		return false;
	}
	print!("{prompt} [y/N] ");
	let _ = std::io::stdout().flush();
	let mut s = String::new();
	std::io::stdin()
		.read_line(&mut s)
		.map(|_| matches!(s.trim().to_lowercase().as_str(), "y" | "yes"))
		.unwrap_or(false)
}

/// Run the setup flow against the local node.
pub fn run(cfg: &Config, opts: &Opts) -> Result<()> {
	let node: &Node = cfg.local_node();
	let models_dir = opts
		.models_dir
		.clone()
		.unwrap_or_else(|| node.models_dir.clone());
	// Must be absolute: this is passed to `sudo mkdir/chown` positionally, so a
	// relative or leading-'-' value would be a relative write or a parsed option.
	if !Path::new(&models_dir).is_absolute() {
		bail!("models_dir must be an absolute path (got `{models_dir}`)");
	}
	let user = opts.user.clone().unwrap_or_else(current_user);
	// `user` is interpolated into `User={user}` in the systemd unit; a newline or
	// whitespace would inject arbitrary unit directives.
	if user.is_empty() || user.starts_with('-') || user.chars().any(|c| c.is_whitespace()) {
		bail!("service user `{user}` is not a valid username");
	}
	let unit = node.llama_unit.clone();
	let unit_body = unit_text(&user);
	let cfg_body = fleet_toml(&models_dir, &unit, &node.llama_url);
	// Never offer to write a config that wouldn't parse back.
	Config::load_str(&cfg_body).context("internal: generated fleet.toml did not parse")?;
	// /etc on a normal install; /run when /etc's unit dir is read-only (the
	// NixOS netboot image) - the same root detection `node load` uses.
	let (unit_path, _unit_dir_str) = if swap::is_root() {
		let unit_dir = swap::unit_install_dir();
		(format!("{unit_dir}/{unit}"), unit_dir.to_string())
	} else {
		let u = crate::platform::user_unit_dir();
		(u.join(&unit).to_string_lossy().to_string(), u.to_string_lossy().to_string())
	};
	if swap::is_root() && swap::unit_install_dir() == swap::RUN_UNIT_DIR {
		println!(
			"[note] /etc/systemd/system is read-only (NixOS image) - units/drop-ins \
			 go to {} (runtime; cleared on reboot)\n",
			swap::RUN_UNIT_DIR
		);
	}

	// Preflight.
	println!("== preflight ({}) ==", node.name);
	let checks = doctor::run(node);
	for c in &checks {
		println!("  {} {:<16} {}", c.status, c.label, c.detail);
	}
	println!();

	if opts.print {
		println!("== {unit_path} (would write if absent) ==\n{unit_body}");
		println!(
			"== {} (would write if absent) ==\n{cfg_body}",
			fleet_path_str()
		);
		println!(
			"== models dir: {models_dir} (exists: {}) ==",
			Path::new(&models_dir).is_dir()
		);
		println!("\n(dry run - nothing written; re-run without --print to apply)");
		return Ok(());
	}

	// 1. Models dir. Create via sudo (it lives under /var/lib) and hand it to the
	// invoking user so models can be dropped in without root.
	if Path::new(&models_dir).is_dir() {
		println!("[ok]   models dir {models_dir} exists");
	} else if confirm(&format!("create models dir {models_dir}?"), opts.assume_yes) {
		swap::sudo(&["mkdir", "-p", "--", &models_dir])?;
		swap::sudo(&["chown", "--", &user, &models_dir])?;
		println!("[ok]   created {models_dir} (owned by {user} - drop GGUFs here, no sudo needed)");
	} else {
		println!("[skip] models dir not created - put GGUFs somewhere and set models_dir");
	}
	println!("\n{}\n", crate::model::where_to_put_models(&models_dir));

	// 2. Base systemd unit or OpenRC service.
	if crate::platform::init::is_systemd() {
		match existing_unit(&unit) {
			Some(p) => println!("[ok]   unit {unit} already present ({})", p.display()),
			None => {
				if confirm(
					&format!("write base systemd unit {unit} (runs as {user})?"),
					opts.assume_yes,
				) {
					if swap::is_root() {
						swap::sudo_tee(Path::new(&unit_path), &unit_body)
							.with_context(|| format!("writing {unit_path}"))?;
						swap::sudo(&["systemctl", "daemon-reload"])?;
					} else {
						if let Some(parent) = Path::new(&unit_path).parent() {
							std::fs::create_dir_all(parent)?;
						}
						std::fs::write(&unit_path, &unit_body)
							.with_context(|| format!("writing {unit_path}"))?;
						let _ = std::process::Command::new("systemctl").args(["--user", "daemon-reload"]).status();
					}
					println!("[ok]   wrote {unit_path} + daemon-reload");
				} else {
					println!("[skip] systemd unit not written - swaps need it to exist");
				}
			}
		}
		// 2b. Safe fallback drop-in - always ensure it, so even a pre-existing or
		// hand-rolled base unit can't crash-loop when no model is loaded. Written
		// to the same root as the unit (/run on the netboot image).
		let dropin_d = swap::dropin_dir(&unit);
		let safe_dropin = dropin_d.join("00-llmtune-safe.conf");
		let limits_dropin = dropin_d.join("01-llmtune-limits.conf");
		if swap::is_root() {
			swap::sudo(&["mkdir", "-p", &dropin_d.to_string_lossy()])?;
			swap::sudo_tee(&safe_dropin, SAFE_FALLBACK_DROPIN)
				.with_context(|| format!("writing {}", safe_dropin.display()))?;
			swap::sudo_tee(&limits_dropin, LIMITS_DROPIN)
				.with_context(|| format!("writing {}", limits_dropin.display()))?;
			swap::sudo(&["systemctl", "daemon-reload"])?;
		} else {
			std::fs::create_dir_all(&dropin_d)?;
			std::fs::write(&safe_dropin, SAFE_FALLBACK_DROPIN)
				.with_context(|| format!("writing {}", safe_dropin.display()))?;
			std::fs::write(&limits_dropin, LIMITS_DROPIN)
				.with_context(|| format!("writing {}", limits_dropin.display()))?;
			let _ = std::process::Command::new("systemctl").args(["--user", "daemon-reload"]).status();
		}
		println!("[ok]   safe fallback + crash-loop guard drop-ins ensured");
	} else {
		let service_name = unit.strip_suffix(".service").unwrap_or(&unit);
		let init_path = format!("/etc/init.d/{service_name}");
		let conf_path = format!("/etc/conf.d/{service_name}");
		if Path::new(&init_path).exists() {
			println!("[ok]   OpenRC init script {init_path} already present");
		} else if confirm(
			&format!("write OpenRC init script {init_path} (runs as {user})?"),
			opts.assume_yes,
		) {
			let init_body = openrc_init_text(&user);
			swap::sudo_tee(Path::new(&init_path), &init_body)
				.with_context(|| format!("writing {init_path}"))?;
			swap::sudo(&["chmod", "+x", &init_path])?;
			println!("[ok]   wrote {init_path} + chmod +x");
		} else {
			println!("[skip] OpenRC init script not written");
		}
		let conf_body = openrc_conf_text(&user);
		swap::sudo_tee(Path::new(&conf_path), &conf_body)
			.with_context(|| format!("writing {conf_path}"))?;
		println!("[ok]   wrote OpenRC conf {conf_path}");
	}

	// 3. fleet.toml.
	match fleet_path() {
		Some(p) if p.is_file() => println!("[ok]   config {} already exists", p.display()),
		Some(p) => {
			if confirm(&format!("write {}?", p.display()), opts.assume_yes) {
				if let Some(dir) = p.parent() {
					std::fs::create_dir_all(dir)?;
				}
				std::fs::write(&p, &cfg_body)
					.with_context(|| format!("writing {}", p.display()))?;
				println!("[ok]   wrote {}", p.display());
			}
		}
		None => println!("[skip] no $HOME - cannot place fleet.toml"),
	}

	// 4. Build Toolchain & Engine.
	let dep = build::check_build_deps();
	if !dep.missing.is_empty() {
		println!("[warn] build toolchain incomplete: missing {}", dep.missing.join(", "));
		if confirm(&format!("install missing build toolchain dependencies ({})?", dep.missing.join(", ")), opts.assume_yes) {
			if let Some(pm) = crate::platform::pkg::detect_pm() {
				let pkgs = crate::platform::pkg::toolchain_packages(&pm);
				if !pkgs.is_empty() {
					println!("[run]  installing build dependencies via {pm}...");
					if let Err(e) = crate::platform::pkg::install_packages(pkgs) {
						println!("[error] failed to install build packages: {e}");
					} else {
						println!("[ok]   installed build toolchain packages");
					}
				}
			} else {
				println!("[skip] no supported package manager detected - run manually: {}", dep.install_cmd);
			}
		}
	}

	if build::current_bin("vulkan", "llama-server").is_some() {
		println!("[ok]   llama.cpp build `vulkan` installed");
	} else if confirm("build and install llama.cpp vulkan engine now?", opts.assume_yes) {
		match build::load().and_then(|specs| {
			let spec = build::spec(&specs, "vulkan")
				.cloned()
				.ok_or_else(|| anyhow::anyhow!("no vulkan build recipe in builds.toml"))?;
			let mut builder = build::RealBuilder::new();
			build::install(&spec, &mut builder, build::DEFAULT_RETAIN)
		}) {
			Ok(out) => println!("[ok]   built and installed vulkan build ({})", out.slug),
			Err(e) => println!("[error] build failed: {e} - run `llmtune build vulkan` when ready"),
		}
	} else {
		println!("[next] build the engine:  llmtune build vulkan");
	}

	println!("\nsetup done. once a build + a model are present:  llmtune node load <name>");
	Ok(())
}

fn fleet_path_str() -> String {
	fleet_path()
		.map(|p| p.display().to_string())
		.unwrap_or_else(|| "~/.config/llmtune/fleet.toml".to_string())
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn unit_text_is_a_valid_skeleton() {
		let u = unit_text("user");
		assert!(u.contains("[Unit]"));
		assert!(u.contains("[Service]"));
		assert!(u.contains("[Install]"));
		assert!(u.contains("User=user"));
		assert!(u.contains("Restart=always"));
		// drop-in overrides this placeholder at load time
		assert!(u.contains("ExecStart=/bin/false"));
		assert!(u.contains("WantedBy=multi-user.target"));
		// Vulkan/DRM access groups
		assert!(u.contains("SupplementaryGroups=video render"));
	}

	#[test]
	fn fleet_toml_carries_the_node_paths() {
		let t = fleet_toml(
			"/home/user/models",
			"llama-server.service",
			"http://127.0.0.1:8080",
		);
		assert!(t.contains("[defaults]"));
		assert!(t.contains("models_dir = \"/home/user/models\""));
		assert!(t.contains("llama_unit = \"llama-server.service\""));
		assert!(t.contains("llama_url  = \"http://127.0.0.1:8080\""));
		// it must parse back as a real config
		let c = crate::config::Config::load_str(&t).expect("generated fleet.toml must parse");
		assert_eq!(c.local_node().models_dir, "/home/user/models");
	}
}
